### PR TITLE
feat(java-shell): allow passing Engine to MongoShell to enable code caching

### PR DESCRIPTION
**Pull request by kornilova203**
Merge after #1250

### CODE REVIEW

**Comment by addaleax** [comment]
@kornilova203 Can you rebase this? I just merged #1250 :)

**Comment by kornilova203** [comment]
@addaleax, done!

**Review by addaleax — APPROVED** [review]

**Comment by kornilova203** [comment]
@addaleax, could you please take a look at failed tests? Are they related?

**Comment by addaleax** [comment]
@kornilova203 Thank you for the ping! Yeah, these seem related:

```
 [2022/03/30 14:18:49.293] com.mongodb.mongosh.LiteralsTest > testSymbol SKIPPED
 [2022/03/30 14:18:49.293] Gradle Test Executor 1 finished executing tests.
 [2022/03/30 14:18:49.893] > Task :test
 [2022/03/30 14:18:49.893] Finished generating test XML results (0.071 secs) into: /data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/build/test-results/test
 [2022/03/30 14:18:49.893] Generating HTML test report...
 [2022/03/30 14:18:49.893] Finished generating test html results (0.1 secs) into: /data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/build/reports/tests/test
 [2022/03/30 14:18:49.893] Watching 772 directories to track changes
 [2022/03/30 14:18:49.893] Watching 778 directories to track changes
 [2022/03/30 14:18:49.893] Watching 779 directories to track changes
 [2022/03/30 14:18:49.893] Stored cache entry for task ':test' with cache key eaf82f76fe1dd9741cd39632c9493ce6
 [2022/03/30 14:18:49.893] :test (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 3 mins 57.355 secs.
 [2022/03/30 14:18:49.893] :inspectClassesForKotlinIC (Thread[Execution worker for ':' Thread 3,5,main]) started.
 [2022/03/30 14:18:49.893] > Task :inspectClassesForKotlinIC
 [2022/03/30 14:18:49.893] Watching 780 directories to track changes
 [2022/03/30 14:18:49.893] Caching disabled for task ':inspectClassesForKotlinIC' because:
 [2022/03/30 14:18:49.893]   Caching has not been enabled for the task
 [2022/03/30 14:18:49.893] Task ':inspectClassesForKotlinIC' is not up-to-date because:
 [2022/03/30 14:18:49.893]   No history is available.
 [2022/03/30 14:18:49.893] Watching 779 directories to track changes
 [2022/03/30 14:18:49.893] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/build/classes/java/main', not found
 [2022/03/30 14:18:49.893] Watching 780 directories to track changes
 [2022/03/30 14:18:49.893] :inspectClassesForKotlinIC (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.023 secs.
 [2022/03/30 14:18:49.893] :jar (Thread[Execution worker for ':' Thread 2,5,main]) started.
 [2022/03/30 14:18:50.593] > Task :jar
 [2022/03/30 14:18:50.593] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/build/classes/java/main', not found
 [2022/03/30 14:18:50.593] Watching 781 directories to track changes
 [2022/03/30 14:18:50.593] Watching 782 directories to track changes
 [2022/03/30 14:18:50.593] Caching disabled for task ':jar' because:
 [2022/03/30 14:18:50.593]   Caching has not been enabled for the task
 [2022/03/30 14:18:50.593] Task ':jar' is not up-to-date because:
 [2022/03/30 14:18:50.593]   No history is available.
 [2022/03/30 14:18:50.593] Watching 781 directories to track changes
 [2022/03/30 14:18:50.593] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/build/classes/java/main', not found
 [2022/03/30 14:18:50.593] Watching 782 directories to track changes
 [2022/03/30 14:18:50.593] :jar (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.747 secs.
 [2022/03/30 14:18:50.593] :cli:compileKotlin (Thread[Execution worker for ':' Thread 2,5,main]) started.
 [2022/03/30 14:18:51.493] > Task :cli:compileKotlin FAILED
 [2022/03/30 14:18:51.493] Watching 783 directories to track changes
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/mongodb-driver-sync/4.2.0/mongodb-driver-sync-4.2.0.pom to /home/ubuntu/.gradle/.tmp/gradle_download1275798420086064049bin
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/bson/4.2.0/bson-4.2.0.pom to /home/ubuntu/.gradle/.tmp/gradle_download1802403197067670691bin
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/mongodb-driver-core/4.2.0/mongodb-driver-core-4.2.0.pom to /home/ubuntu/.gradle/.tmp/gradle_download2294566324535686867bin
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/mongodb-driver-sync/4.2.0/mongodb-driver-sync-4.2.0.jar to /home/ubuntu/.gradle/.tmp/gradle_download7807471982566044556bin
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/mongodb-driver-core/4.2.0/mongodb-driver-core-4.2.0.jar to /home/ubuntu/.gradle/.tmp/gradle_download1756658294770724897bin
 [2022/03/30 14:18:51.493] Downloading https://repo.maven.apache.org/maven2/org/mongodb/bson/4.2.0/bson-4.2.0.jar to /home/ubuntu/.gradle/.tmp/gradle_download8393564176104211374bin
 [2022/03/30 14:18:51.493] Watching 789 directories to track changes
 [2022/03/30 14:18:51.493] Watching 789 directories to track changes
 [2022/03/30 14:18:51.493] Custom actions are attached to task ':cli:compileKotlin'.
 [2022/03/30 14:18:51.493] Build cache key for task ':cli:compileKotlin' is f963c4f2ee72a7864fd2b8e37418479d
 [2022/03/30 14:18:51.493] Task ':cli:compileKotlin' is not up-to-date because:
 [2022/03/30 14:18:51.493]   No history is available.
 [2022/03/30 14:18:51.493] Watching 788 directories to track changes
 [2022/03/30 14:18:51.493] The input changes require a full rebuild for incremental task ':cli:compileKotlin'.
 [2022/03/30 14:18:51.493] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/src/main/java', not found
 [2022/03/30 14:18:51.493] Using Kotlin/JVM incremental compilation
 [2022/03/30 14:18:51.493] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/src/main/java', not found
 [2022/03/30 14:18:51.493] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/src/main/java', not found
 [2022/03/30 14:18:51.493] file or directory '/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/src/main/java', not found
 [2022/03/30 14:18:51.493] [KOTLIN] Kotlin compilation 'jdkHome' argument: /usr/lib/jvm/java-8-openjdk-amd64
 [2022/03/30 14:18:51.493] i: found daemon on port 17614 (266403 ms old), trying to connect
 [2022/03/30 14:18:51.493] i: connected to the daemon
 [2022/03/30 14:18:51.493] Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0], reportSeverity=2, requestedCompilationResults=[0]kotlinScriptExtensions=[kt, kts, java]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, classpathChanges=org.jetbrains.kotlin.incremental.ClasspathChanges$NotAvailable$ClasspathSnapshotIsDisabled@6883947b, workingDir=/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/build/kotlin/compileKotlin, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/build/kotlin/compileKotlin/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=trueoutputFiles=[/data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/build/classes/kotlin/main, /data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/build/kotlin/compileKotlin])
 [2022/03/30 14:18:51.493] Restoring task outputs to pre-compilation state
 [2022/03/30 14:18:51.493] Watching 790 directories to track changes
 [2022/03/30 14:18:51.493] :cli:compileKotlin (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.82 secs.
 [2022/03/30 14:18:51.493] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
 [2022/03/30 14:18:51.493] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
 [2022/03/30 14:18:51.493] See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings
 [2022/03/30 14:18:51.493] 10 actionable tasks: 10 executed
 [2022/03/30 14:18:51.493] Watching 789 directories to track changes
 [2022/03/30 14:18:51.493] Not watching anything anymore
 [2022/03/30 14:18:51.493] Watching 0 directories to track changes
 [2022/03/30 14:18:51.493] e: /data/mci/5251e3a11480330d7ad945fcf5a79b1b/src/packages/java-shell/cli/src/main/kotlin/com/mongodb/mongosh/cli/main.kt: (23, 16): Cannot access class 'org.graalvm.polyglot.Engine'. Check your module classpath for missing or conflicting dependencies
 [2022/03/30 14:18:51.493] FAILURE: Build failed with an exception.
 [2022/03/30 14:18:51.493] * What went wrong:
 [2022/03/30 14:18:51.493] Execution failed for task ':cli:compileKotlin'.
 [2022/03/30 14:18:51.493] > Compilation error. See log for more details
 [2022/03/30 14:18:51.493] * Try:
 [2022/03/30 14:18:51.493] Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
 [2022/03/30 14:18:51.493] * Get more help at https://help.gradle.org
 [2022/03/30 14:18:51.494] BUILD FAILED in 5m 59s
```

I assume the `Cannot access class 'org.graalvm.polyglot.Engine'.` line is the relevant problem here, if you need the full log I can send it to you on Slack

**Comment by kornilova203** [comment]
@addaleax, yeah, I forgot to compile `cli` subproject
I've just pushed a fix

**Pull request merged**
