### PR TITLE
test: Stream logs from lerna when running tests

### PR DESCRIPTION
**Pull request by gribnoysup**
When lerna runs all the tests in parallel, sometimes the log output between different packages is overlapping, producing a very hard to dechipher log ("Is this line is still from package A or is it package B run output that got in the middle?"). Enabling stream option seems to produce a more readable result where every line is prepended by the package name that runs the script. This helped me a lot to debug the "stuck process" issue in #533 and I thought that it would be nice to have this enabled by default for our test scripts that are run by lerna.

For an example of overlapping logs here's a part of the log of this PR ci run:

image

There are 5 packages logs overlapped together

### CODE REVIEW

**Comment by gribnoysup** [comment]
The patch actually succeeded after a re-run, but seems like evergreen is not able to update the status

**Review by addaleax — APPROVED** [review]

**Comment by addaleax** [comment]
> The patch actually succeeded after a re-run, but seems like evergreen is not able to update the status

I think that's just because there's still one win32 task running. :) (But feel free to merge it already if you like.)

**Comment by gribnoysup** [comment]
Oh, you're right, I think I might've looked at a different run when I wrote that! Hmm, something seems off about this one task being stuck with this change, I'll wait a little before merging to make sure I'm not breaking the ci again 😅

**Review by aherlihy — APPROVED** [review]
I've been having some trouble with that test being flaky in other PRs, so I would guess it's not anything in this PR

**Comment by gribnoysup** [comment]
Ah, good to know, thanks! Well, merging then 👍

**Comment by addaleax** [comment]
Is it possible that this is causing the test timeouts on Windows (there are a few in https://evergreen.mongodb.com/waterfall/mongosh)?

**Comment by gribnoysup** [comment]
I'm not sure why this would be the cause, but yeah, tests in this branch timed-out a few times and it seems this wasn't just a flaky test after all. I'll revert the patch

**Pull request merged**
