### PR TITLE
chore: use prettier MONGOSH-1482 

### PR DESCRIPTION
**Pull request by lerouxb**
replaces https://github.com/mongodb-js/mongosh/pull/1504

* Just like in compass we'll now run prettier on all the changed files when committing. Via a precommit hook provided by husky.
* The shared prettier config is now used everywhere.
* lint runs eslint and prettier check
* reformat runs prettier and eslint fix
* prettier reformatted all our code 😬

### CODE REVIEW

**Review by addaleax — APPROVED** [review]

**Comment by gribnoysup** [comment]
Hmmm, my assumption would be that everything that is prettier ignored is also git ignored and so shouldn't be caught by the precommit hook 🤔 What was the case where this didn't work out?

**Comment by lerouxb** [comment]
@gribnoysup test fixtures.

**Comment by lerouxb** [comment]
I think I'll just merge this for now because I finally got it green. If we can think of a better solution for .prettierignore I'll just open more PRs.

**Comment by gribnoysup** [comment]
Totally, having the config at root sounds good to me anyway, just a bit unexpected so I was curious what's the case where this happens

**Pull request merged**
