### PR TITLE
fix(cli-repl): do not require password for GSSAPI authentication MONGOSH-899

### PR DESCRIPTION
**Pull request by rose-m**
Also verified to test with Kerberos on Windows.

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
Is there any chance we could add a test for this, either here or on the Node.js side? An option having different behavior between being `undefined` vs not being present at all seems like the kind of thing that a driver change could accidentally break very easily

**Comment by rose-m** [comment]
Yeah I'm not sure how to best test it... The Kerberos connectivity tests already work without a password as the `askpassword` handles that with an empty password it seems. The only thing I could do is to verify in there that it even does not ask for a password anymore...?

**Comment by rose-m** [comment]
@addaleax Yeah I'll try add a test case to the driver for that 👍 Would then merge this PR.

**Comment by addaleax** [comment]
@rose-m Yes, please feel free to do so :)

**Pull request merged**
