### PR TITLE
fix(cli-repl): re-add aws4 as dependency to cli-repl to enable AWS auth

### PR DESCRIPTION
**Pull request by denise-sanders**
When I used mongosh with aws roles I got the below error in the screenshot attached.

I saw that this package was added it this earlier pr
https://github.com/mongodb-js/mongosh/pull/718/files
and removed in this one
https://github.com/mongodb-js/mongosh/pull/959/files

Screen Shot 2021-11-05 at 10 53 26 AM

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
Thank you! Out of curiousity, what environment are you running this on? I assume it’s not the mongosh binary downloaded from https://www.mongodb.com/try/download/shell, right?

**Comment by addaleax** [comment]
@denise-sanders If you haven’t done so already, could you sign the [MongoDB contributor’s agreement](https://www.mongodb.com/contributor)? I don’t think this type of PR would strictly require it but it might still be good to have to be sure.

**Comment by denise-sanders** [comment]
Hi @addaleax !

I did sign the agreement but i used a different email (same github username though)

I installed mongosh through brew, mms is a script I have that builds a connection string based on cli params (I connect to multiple clusters) then just calls mongosh with that string

**Comment by addaleax** [comment]
@denise-sanders Thanks, that makes sense then! I’ll merge this once CI is green.

**Comment by addaleax** [comment]
@denise-sanders Just fyi, this is included in mongosh 1.1.2 which has just been released -- Thank you again for the PR! 🙂

**Pull request merged**
