### PR TITLE
MONGOSH-385: Show deprecation warnings for deprecated CRUD methods from shell API

### PR DESCRIPTION
**Pull request by gribnoysup**
This PR ~removes~ prints deprecation message when calling deprecated `save`, `remove`, `update`, and `insert` methods from shell api

### CODE REVIEW

**Review by aherlihy — APPROVED** [review]
LGTM! Because it touches so much of the java-shell I'd like @kornilova203 to take a look as well before we merge :)

**Review by lrlna — CHANGES_REQUESTED** [review]
We ought to also remove `insert` and `remove` documentation from the `i18n` package imo. Just so users don't end up thinking it's still there when it's not.

_Edit`_ : `insert`, `remove`, `save` and `update`.

**Comment by gribnoysup** [comment]
Oh, good catch, thanks, will definitely remove it from there!

**Comment by kornilova203** [comment]
I'll take a look tomorrow
BTW why there is no deprecation warning in documentation? e.g. https://docs.mongodb.com/manual/reference/method/db.collection.insert/

**Comment by gribnoysup** [comment]
Thanks @kornilova203! Sorry for the diff being so big, this change touched almost every test file in `java-shell`, on the plus side, most of the expectation files are untouched and the tests are passing, so not that much actually changed in terms how anything works 😄 

As for the deprecation documentation of the shell it's all a little bit convoluted, but from my understanding in current `mongo` shell only one of those methods marked as deprecated, but we are aligning more here with [crud spec](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst) and [drivers implementation](https://mongodb.github.io/node-mongodb-native/3.6/api/) and there these methods are deprecated. @aherlihy please correct me if I'm misinterpreting something here!

**Review by kornilova203 — APPROVED** [review]

**Comment by kornilova203** [comment]
@gribnoysup,
Thank you

Looks good

I'm concerned that JetBrains IDE users don't know that these methods were deprecated.
I'll probably bring methods back in next java-shell release branch and show deprecation warning to IDE users.
After some time I'll remove them also from java-shell

**Review by lrlna — APPROVED** [review]

**Comment by aherlihy** [comment]
yeah, it's a good point that it's deprecated in all the drivers but not deprecated in the shell. perhaps we should add a warning so the user gets 'insert is deprecated, use insertOne or insertMany' instead of 'method not found'?

**Comment by gribnoysup** [comment]
As discussed, returned all removed methods and added deprecation warning printing:

Kapture 2020-11-17 at 09 23 02

**Review by mcasimir — APPROVED** [review]
Nice!

**Review by addaleax — APPROVED** [review]

**Review by aherlihy — APPROVED** [review]

**Pull request merged**
