### PR TITLE
chore(deps): bump to bson@4.6.2

### PR DESCRIPTION
**Pull request by leorossi**

### CODE REVIEW

**Comment by addaleax** [comment]
@leorossi This looks like it was made with npm@7.x?

**Comment by leorossi** [comment]
@addaleax yes, what version should I use instead?

**Comment by addaleax** [comment]
@leorossi We’re still on npm 6 in mongosh until we do MONGOSH-975, unfortunately :confused:

**Comment by leorossi** [comment]
@addaleax ran again with npm 6

**Comment by addaleax** [comment]
@leorossi This seems good, but I think you want to bump it for the `bson` libraries inside the individual packages as well, right?

**Review by addaleax — APPROVED** [review]

**Pull request merged**
