### PR TITLE
revert removing pino-pretty

### PR DESCRIPTION
**Pull request by aherlihy**
I can't run compile-exec anymore on master, I get:

```
node --version v14.15.1
mongosh: writing analytics template: /Users/anna/mongosh/packages/cli-repl/lib/analytics-config.js
mongosh: creating bundle: /Users/anna/mongosh/packages/cli-repl/dist/mongosh.js
🚨  /Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js: ENOENT: no such file or directory, open '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js'
Error: ENOENT: no such file or directory, open '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js'

/Users/anna/mongosh/scripts/compile-exec.js:21
  (err) => process.nextTick(() => { throw err; }));
                                    ^
{
  message: "ENOENT: no such file or directory, open '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js'",
  stack: "Error: ENOENT: no such file or directory, open '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js'",
  name: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js',
  fileName: '/Users/anna/mongosh/packages/cli-repl/node_modules/pino-pretty/index.js'
}
```

### CODE REVIEW

**Comment by addaleax** [comment]
This is odd, there is no mention of `pino-pretty` in the source code anywhere? Do you think you could figure out where `pino-pretty` is being used from?

**Comment by aherlihy** [comment]
I tried, I couldn't find where it was used but the error is also pretty cryptic. I assume there's some dependency that needs it and it's not indicated in their dependencies? I'm not sure, we can make a ticket to investigate but since it's broken in master I figured a quick fix is better

**Comment by aherlihy** [comment]
https://jira.mongodb.org/browse/MONGOSH-491

**Comment by addaleax** [comment]
@aherlihy Yeah, you can go ahead and merge this, but it’s odd that it only reproduces for you (or at least not for me or in CI)? That’s what mostly worries me here, and I don’t think there’s anything we can do to act on that ticket without your help :)

**Comment by aherlihy** [comment]
Oh interesting, you don't have this problem when you do a clean clone from master?

**Comment by addaleax** [comment]
So … if I do `npm run bootstrap && npm run compile-ts && npm run compile-exec` on a completely fresh checkout, then the bundling completes without issues, both on Ubuntu and macOS, sorry … :confused:

**Comment by aherlihy** [comment]
No sorry needed, it's good that it's working! I have no idea why it's broken for me then

**Pull request closed without merging**
