### PR TITLE
chore(java-shell): update MongoDB Java Driver to 4.4.0

### PR DESCRIPTION
**Pull request by kornilova203**

### CODE REVIEW

**Review by addaleax — APPROVED** [review]

**Comment by addaleax** [comment]
@kornilova203 There are some failures here:

On the latest server version (latest alpha and 5.0.x):

```
 [2022/02/04 18:33:41.795] com.mongodb.mongosh.DbTest > testCreateCollection FAILED
 [2022/02/04 18:33:41.795]     org.junit.ComparisonFailure: expected:<...lidation', details={[]}}.> but was:<...lidation', details={["failingDocumentId": {"$oid": "61fd71855f444c283eb09869"}, "details": {"operatorName": "$jsonSchema", "schemaRulesNotSatisfied": [{"operatorName": "properties", "propertiesNotSatisfied": [{"propertyName": "status", "description": "can only be one of the enum values", "details": [{"operatorName": "enum", "specifiedAs": {"enum": ["Unknown", "Incomplete"]}, "reason": "value was not found in enum", "consideredValue": "Updated"}]}]}, {"operatorName": "required", "specifiedAs": {"required": ["phone"]}, "missingProperties": ["phone"]}]}]}}.>
```

On 4.0.x:

```
[2022/02/04 18:27:50.203] com.mongodb.mongosh.CollectionTest > testUniqueIndex FAILED
[2022/02/04 18:27:50.203]     org.junit.ComparisonFailure: expected:<...ongoWriteException: [E11000 duplicate key error collection: admin.coll index: category_1 dup key: { : "cat1" }]> but was:<...ongoWriteException: [Write operation error on server %mongohostport%. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: admin.coll index: category_1 dup key: { : "cat1" }', details={}}.]>
```

Let me know if you can address those or if you would prefer for us to look into them :)

**Comment by kornilova203** [comment]
@addaleax, thanks!
I've pushed couple of commits that should fix all tests.
Let's run tests one more time - if they succeed feel free to squash all the commits
if not then send me errors once again

**Comment by addaleax** [comment]
Now it’s only failing for the server RC (https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1804-latest.tgz):

```
[2022/02/07 13:28:22.987] com.mongodb.mongosh.DbTest > testCreateCollection FAILED
[2022/02/07 13:28:22.987]     org.junit.ComparisonFailure: expected:<...Name": "status", "de[]tails": [{"operatorN...> but was:<...Name": "status", "de[scription": "can only be one of the enum values", "de]tails": [{"operatorN...>
 ```

**Comment by kornilova203** [comment]
@addaleax, I've pushed one more commit

**Comment by addaleax** [comment]
All green now :)

**Pull request merged**
