### PR TITLE
build(node-runtime-worker-thread, compass-shell): Do not inline worker-runtime modules

### PR DESCRIPTION
**Pull request by gribnoysup**
This PR refactors `node-runtime-worker-thread` bundling process to not inline worker source and keep the package as external/peer dependency in the bundle of `compass-shell`. I spent some time digging into bundling of electron apps and this approach is something that I somehow completely missed as possible during the initial implementation.

Benefits of this approach is a simplified build pipeline for the library itself, no need to maintain a custom webpack loader and in theory this should unblock (or definitely make much easier) the inclusion of the `interruptor` with the library eventually.

Downside is a bit cumbersome way of importing worker source in the library that relies on the files staying close together in one place and the need to keep in mind that the runtime is now a peer dependency of the compass shell, but both are pretty small downsides in my opinion compared to the simplification of the whole thing.

(The PR base branch is #572 to avoid conflicts between the two if branched from master)

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
This LGTM, although I have to admit that I'm not fully clear on how the move from a regular dependency to a peer dependency comes into play here (the compass-shell package is still the only consumer of node-runtime-worker-thread, right?). If you want, feel free to enlighten me, but either way I know that you have thought this through :)

**Comment by gribnoysup** [comment]
Ah, that's a good point that it's not clear. So the reason for this is that by default when library is a peer dependency compass plugin in "production" mode will exclude it from the bundle (I _think_ it's part of the default compass plugin template, not only a `compass-shell` thing):

https://github.com/mongodb-js/mongosh/blob/4f1e18f77cb6518a0b3924823822e3596dc5db75/packages/compass-shell/config/webpack.prod.config.js#L67-L69

I was initially thinking that if this externals plugin is already there, I can move the dep to peer deps and be done with it, eventually I had to manually apply the `externals` exception in the "dev" config also. You're right that it will be only used by compass-shell and thinking this over again, I'm leaning to moving it back to deps and making an explicit externals record for the `node-runtime-worker-thread` in the "base" config

**Comment by addaleax** [comment]
> I'm leaning to moving it back to deps and making an explicit externals record for the `node-runtime-worker-thread` in the "base" config

Okay, if that works then I think that sounds a bit more straightforward, but in the end, the important thing is that it works :)

**Comment by gribnoysup** [comment]
Okay, moved it back to deps and moved the `externals` option to base config. Will merge without waiting for ci as nothing really changed and previous run passed

**Pull request merged**
